apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-w3zt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-w3zt@sha256:54a05d4f8be963e155a6a67dd0159fed97a07489f05c3cc3572fc3ef4baf56dd
        name: my-nodejs
        resources: {}
status: {}
